# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7529664cc91267e96de09cf13ea27308f149dc36cb7c25707e43c3fafa3c5549cfde65a48553fd2d01f14a3f9271a516245146e515d9101bcd16711c7d15ba3

test:
  secret_key_base: 95475682a92f1dad93095740f86683efbea00bacc5b6eaab70886d866ac0d5d7bfbe18362b560f8301df3aceab06643245b4bfdf78a53c82e74e2a834fb71c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
